name: Run AWS Spec tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  packages: write

jobs:        
  run-aws-test-kitchen:
    uses: hutchic-observe-meta/aws-test-kitchen/.github/workflows/ci.yml@main
    with:
      test_type: terraform
      code_sha: ${{ github.sha }}
    secrets:
      OBSERVE_CUSTOMER: ${{ secrets.OBSERVE_CUSTOMER }}
      OBSERVE_TOKEN: ${{ secrets.OBSERVE_TOKEN }}
      OBSERVE_DOMAIN: ${{ secrets.OBSERVE_DOMAIN }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
